### ISSUE TITLE
Docs build cleanup & migration to OAI3

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/workflow-execution-service-schemas#145]
Issues:
- [x] #43: [Bump to OpenAPI 3.0](#43)
- [ ] #71: [Document versioning](#71)
- [x] #126: [Update CI build config to match DRS repo](#126)
- [x] #128: [Update README and CONTRIBUTING to match DRS repo](#128)
- [ ] #137: [Create JSON Schema spec from Swagger model definitions during docs build](#137)
- [x] #139: [Swagger UI and Swagger Editor links in README.rst does not work](#139)
- [x] #142: [https://ga4gh.cloud does not resolve](#142)

PRs:
- [x] #140: [Bump swagger-ui from 2.2.10 to 3.23.11](#140)
- [x] #143: [Bump OAPI 2 to OAPI3 (Autogenerated)](#143)

**Comment by jaeddy** [comment]
Ideally, most of the issues/PRs here should be unblocked by in-progress work with [this repo](https://github.com/ga4gh/gh-openapi-docs).

**Comment by jaeddy** [comment]
#71 and #137 are a slightly different scope. Otherwise, I'm considering this issue fixed by #150 and #151.
