### ISSUE TITLE
service-info API integration

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/workflow-execution-service-schemas#146]
Issues:
- [ ] #119: [Improve `service-info` to enable service discovery](#119)
- [ ] #125: [Clean up `service-info` based on AMED feedback](#125)

PRs:
- [x] #144: [Implementing GA4GH Service-Info for WES](#144)

**Comment by jaeddy** [comment]
This has technically been fixed by #150 and #151; #119 and #125 might still be worth addressing separately.
